import type { Photo } from '../app/shared/models/photo.model';

/** Shared factory for `photo-card` and `photo-tooltip` specs. Defaults are
 *  mostly null/falsy, matching what a freshly-scanned photo without the
 *  optional metric columns looks like. */
export const makePhoto = (overrides: Partial<Photo> = {}): Photo => ({
  path: '/test.jpg',
  filename: 'test.jpg',
  aggregate: 7.5,
  aesthetic: 8.0,
  face_quality: null,
  comp_score: null,
  tech_sharpness: null,
  color_score: null,
  exposure_score: null,
  quality_score: null,
  topiq_score: null,
  isolation_bonus: null,
  face_count: 0,
  face_ratio: 0,
  eye_sharpness: null,
  face_sharpness: null,
  face_confidence: null,
  is_blink: null,
  camera_model: null,
  lens_model: null,
  iso: null,
  f_stop: null,
  shutter_speed: null,
  focal_length: null,
  noise_sigma: null,
  contrast_score: null,
  dynamic_range_stops: null,
  mean_saturation: null,
  mean_luminance: null,
  histogram_spread: null,
  composition_pattern: null,
  power_point_score: null,
  leading_lines_score: null,
  category: null,
  tags: null,
  tags_list: [],
  is_monochrome: null,
  is_silhouette: null,
  date_taken: null,
  image_width: 1920,
  image_height: 1080,
  is_burst_lead: null,
  burst_group_id: null,
  duplicate_group_id: null,
  persons: [],
  unassigned_faces: 0,
  star_rating: null,
  is_favorite: null,
  is_rejected: null,
  aesthetic_iaa: null,
  face_quality_iqa: null,
  liqe_score: null,
  subject_sharpness: null,
  subject_prominence: null,
  subject_placement: null,
  bg_separation: null,
  ...overrides,
});

/** Same shape as {@link makePhoto}, but with every metric field the base
 *  fixture leaves null/falsy set to a realistic non-falsy value, so the
 *  `@if (p.X !== null)` render paths gated on them get exercised at least
 *  once. `face_count`/`face_quality` are set alongside `face_sharpness`/
 *  `eye_sharpness` because the template only renders that pair once a face
 *  with a quality score is present. */
export const makePhotoFull = (overrides: Partial<Photo> = {}): Photo => makePhoto({
  quality_score: 8.2,
  topiq_score: 7.6,
  face_count: 1,
  face_quality: 8.4,
  face_sharpness: 8.1,
  eye_sharpness: 8.9,
  noise_sigma: 2.4,
  contrast_score: 6.8,
  dynamic_range_stops: 9.5,
  histogram_spread: 5.3,
  power_point_score: 6.1,
  leading_lines_score: 5.4,
  subject_placement: 6.7,
  unassigned_faces: 2,
  ...overrides,
});
